version: '3.1'
services:
  ptm-mongo:
    image: mongo
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ptm-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${RDS_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${RDS_PASSWORD}
      - MONGO_INITDB_DATABASE=ptm
    ports:
      - '27017:27017'

volumes:
  ptm-data: